config/routes.rb
Rails.application.routes.draw do
  resources :teams_soccers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/teams_soccer.rb
class TeamsSoccer < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/teams_soccers_controller.rb
class TeamsSoccersController < ApplicationController
  before_action :set_teams_soccer, only: %i[ show edit update destroy ]

  # GET /teams_soccers or /teams_soccers.json
  def index
    @teams_soccers = TeamsSoccer.all
  end

  # GET /teams_soccers/1 or /teams_soccers/1.json
  def show
  end

  # GET /teams_soccers/new
  def new
    @teams_soccer = TeamsSoccer.new
  end

  # GET /teams_soccers/1/edit
  def edit
  end

  # POST /teams_soccers or /teams_soccers.json
  def create
    @teams_soccer = TeamsSoccer.new(teams_soccer_params)

    respond_to do |format|
      if @teams_soccer.save
        format.html { redirect_to teams_soccer_url(@teams_soccer), notice: "Teams soccer was successfully created." }
        format.json { render :show, status: :created, location: @teams_soccer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @teams_soccer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams_soccers/1 or /teams_soccers/1.json
  def update
    respond_to do |format|
      if @teams_soccer.update(teams_soccer_params)
        format.html { redirect_to teams_soccer_url(@teams_soccer), notice: "Teams soccer was successfully updated." }
        format.json { render :show, status: :ok, location: @teams_soccer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @teams_soccer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams_soccers/1 or /teams_soccers/1.json
  def destroy
    @teams_soccer.destroy

    respond_to do |format|
      format.html { redirect_to teams_soccers_url, notice: "Teams soccer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teams_soccer
      @teams_soccer = TeamsSoccer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def teams_soccer_params
      params.require(:teams_soccer).permit(:title, :description, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/teams_soccers_helper.rb
module TeamsSoccersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrazilianSoccerTeam</title>

      <style>
        body {background-color: gray;}
        h1   {color: blue;}
        p   {color: black; }
        h3  {color: orange;}
        h3  {color: orange;}
        
        <br>
        </style> <br>


        <%# ########################################################## %>

        

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/teams_soccers/_form.html.erb
<%= form_with(model: teams_soccer) do |form| %>
  <% if teams_soccer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(teams_soccer.errors.count, "error") %> prohibited this teams_soccer from being saved:</h2>

      <ul>
        <% teams_soccer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_field :text %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/teams_soccers/_teams_soccer.html.erb
<div id="<%= dom_id teams_soccer %>">
  <p>
    <strong>Time Name:</strong>
    <%= teams_soccer.title %>
  </p>

  <p>
    <strong>History:</strong>
    <%= teams_soccer.description %>
  </p>

  <p>
    <strong>Hino:</strong>
    <%= teams_soccer.text %>
  </p>

</div>

app/views/teams_soccers/edit.html.erb
<h1>Editing teams soccer</h1>

<%= render "form", teams_soccer: @teams_soccer %>

<br>

<div>
  <%= link_to "Show this teams soccer", @teams_soccer %> |
  <%= link_to "Back to teams soccers", teams_soccers_path %>
</div>

app/views/teams_soccers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Teams soccers</h1>

<div id="teams_soccers">
  <% @teams_soccers.each do |teams_soccer| %>
    <%= render teams_soccer %>
    <p>
      <%= link_to "Show this teams soccer", teams_soccer %>
    </p>
  <% end %>
</div>

<%= link_to "New teams soccer", new_teams_soccer_path %>

app/views/teams_soccers/new.html.erb
<h1>New teams soccer</h1>

<%= render "form", teams_soccer: @teams_soccer %>

<br>

<div>
  <%= link_to "Back to teams soccers", teams_soccers_path %>
</div>

app/views/teams_soccers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @teams_soccer %>

<div>
  <%= link_to "Edit this teams soccer", edit_teams_soccer_path(@teams_soccer) %> |
  <%= link_to "Back to teams soccers", teams_soccers_path %>

  <%= button_to "Destroy this teams soccer", @teams_soccer, method: :delete %>
</div>